### ISSUE TITLE
Бинарники в релизе

### ISSUE THREAD

**Issue by Chiliec** [asuleymanov/witness_go#1]
Мало кому из непрограммистов хочется ставить что-то дополнительно. Можно же бинарники положить в релиз?

**Comment by asuleymanov** [comment]
Вот только вопрос под какую систему компилировать?

**Comment by Chiliec** [comment]
Думаю, что надо исходить из того где предполагается запуск этого приложения.

**Comment by asuleymanov** [comment]
Да это мысль сейчас поправлю.

**Comment by asuleymanov** [comment]
Поправил. Добавил информацию в посте
