### ISSUE TITLE
Поломалось обновление прайсфидов

### ISSUE THREAD

**Issue by muhazzz** [asuleymanov/witness_go#3]
![screenshot-2018-06-21-13-32-12](https://user-images.githubusercontent.com/19325076/41701706-a109f60c-7557-11e8-972e-6fdea6929da1.png)

Возможно, причина в том, что поменялся namespace у функции, теперь он witness_api

**Comment by muhazzz** [comment]
P.S.: А вообще, и witness_go и golos-go -- суперские, пользуюсь с огромным удовольствием. Спасибо!

**Comment by asuleymanov** [comment]
Приветствую.
Попробую сегодня до вечера исправить данную проблему.

**Comment by muhazzz** [comment]
Есть ещё смысл надеяться на исправления "до вечера"? :)

**Comment by asuleymanov** [comment]
Здравствуйте.
Приношу извинения за то что еще не исправил данную проблему.
Обновление будет обязательно сделано так как от этого зависит работоспособность моей ноды.

**Comment by asuleymanov** [comment]
Еще раз приношу свои извинения за задержку.
Проблема исправлена. И все работает нормально.
Только если компилировать необходимо перекачать новую библиотеку.

**Comment by muhazzz** [comment]
Да, работает, спасибо!
