### ISSUE TITLE
Альтернативная установка GO для witness_go

### ISSUE THREAD

**Issue by jackvote** [asuleymanov/witness_go#4]
Устанавливается не самая последняя версия, но штатными средствами Ubuntu
$ sudo add-apt-repository ppa:longsleep/golang-backports
$ sudo apt-get update
$ sudo apt-get install golang-go
$ go version
version go1.10.1 linux/amd64

Для сборки wintness_go требуется ещё добавить нижеследующее.
$ sudo go get golang.org/x/net/html
$ sudo go get golang.org/x/text
И теперь можно в каталоге ../witness_go делать 
$ go build

Сборка производится. Скрипт работает.
$ witness_go settings
выдаёт информацию.
А вот 
$ witness_go feed
не получается.
Только вот что-то с ключами я напутал? В лог пишется:

2018/09/13 12:17:34 Стоимость GOLOS в рублях : 1.32335447
2018/09/13 12:17:34 Стоимость GOLD в рублях : 2.66485000
2018/09/13 12:17:34 Feed Publish -> 0.497 GBG
2018/09/13 12:17:34 error decode Active Key: failed to decode WIF: malformed private key
2018/09/13 12:17:34 error decode Active Key: failed to decode WIF: malformed private key

Активный ключ указан тот, которым я делаю транзакции.
GLS-ключ также указан.

Может это как раз из-за неактуальной версии Go?
Ведь не требуется стартовать (witness_go start) перед Feed Publish?

**Comment by jackvote** [comment]
Проблема найдена в описании:

> Произвести настройки в файле witness.conf 

Файл должен называться witness_go.conf

**Comment by asuleymanov** [comment]
Да признаю.
Некорректно написан мануал.
Спасибо большое за Ваше обращение.

Проблемму с описанием исправил.
